@startuml Prototype_Pattern
interface Prototype {
    + clone(): Prototype
}

class ConcretePrototypeA {
    + clone(): ConcretePrototypeA
}

class ConcretePrototypeB {
    + clone(): ConcretePrototypeB
}

Prototype <|.. ConcretePrototypeA
Prototype <|.. ConcretePrototypeB

@enduml
