@startuml State_Pattern
interface State {
    + handle(context: Context): void
}

class Context {
    - state: State
    + set_state(state: State): void
    + request(): void
}

class ConcreteStateA {
    + handle(context: Context): void
}

class ConcreteStateB {
    + handle(context: Context): void
}

State <|.. ConcreteStateA
State <|.. ConcreteStateB

Context --> State : state

@enduml
